create table Users(
    id int generated by default as identity,
    username varchar(255) not null,
    email varchar(255) not null,
    password varchar(255) not null,
    primary key (id)
);

alter table users add constraint unique_username unique (username);
alter table users add constraint unique_email unique (email);

create table Posts(
    id int generated by default as identity,
    user_id int references Users(id) on delete cascade,
    title varchar(255) not null,
    content varchar(2048),
    created_at timestamp default current_timestamp,
    updated_at timestamp default current_timestamp,
    primary key (id)
);

create table PostImages(
    id int generated by default as identity,
    post_id int not null references Posts(id) on delete cascade,
    image_url varchar(255) not null,
    primary key (id)
);
